### ISSUE TITLE
remove swipe in header view

### ISSUE THREAD

**Issue by atnpem** [akiroom/AXStretchableHeaderTabViewController#10]
It's possible to not consider the swipe in headerview zone ?

**Comment by akiroom** [comment]
Yes, you can ignore horizontal swipe in header view by the following code.

```
// MyHeaderView.m

- (id)initWithFrame:(CGRect)frame
{
  if (self = [super initWithFrame:frame]) {
    self.delegate = self;
  }
  return self;
}

- (NSArray *)interactiveSubviewsInStretchableHeaderView:(AXStretchableHeaderView *)stretchableHeaderView
{
  return @[self];
}
```

**Comment by atnpem** [comment]
Ok, I try, but this code not work. I'll investigate. Thx.

**Comment by akiroom** [comment]
Sorry. I investigated it, and found my bug. I'm going to fix it now.

**Comment by akiroom** [comment]
I've fixed this bug in the above commit.
From latest ver 0.1.8, you can make non-swipable header view to set `nil` in `AXStretchableHeaderView`#`delegate`.
Please look at `AXSampleNoSwipableTabViewController` class in example project.

**Comment by atnpem** [comment]
Hi, Great for the left and right swipe, but It is unfortunate that the scroll down and up is disabled on the header. Thanks for you fix ;)
