### ISSUE TITLE
UITableViewController only

### ISSUE THREAD

**Issue by kutakmir** [akiroom/AXStretchableHeaderTabViewController#14]
Is there a way how to use also UIViewController with embedded UITableView or UIScrollView the same way as UITableViewController?
The header responds only to this class so far..

**Comment by kutakmir** [comment]
I'd suggest to replace viewController.view with this function:

```
- (UIScrollView *)scrollViewFromHierarchyOfViewController: (UIViewController *)controller
{
    // Get selected scroll view.
    UIScrollView *scrollView = (id)controller.view;
    if (![scrollView isKindOfClass:[UIScrollView class]]) {
        for (UIView *subview in [self selectedViewController].view.subviews) {
            if ([subview isKindOfClass:[UIScrollView class]]) {
                scrollView = (id)subview;
                break;
            }
        }
    }

    return scrollView;
}
```

**Comment by kutakmir** [comment]
or even better by providing a view for each controller, so that for example UINavigationController can be embedded and therefore Instagram gallery picker effect can be achieved!

That would make the library even cooler!!

**Comment by akiroom** [comment]
Thank you for your advice.
Now, I implemented `AXStretchableSubViewControllerViewSource` protocol, from version 0.9.0.
You can represent which view is UIScrollView by this protocol.
Please check `AXSub4ViewController.h` and `AXSub4ViewController.m` in example.

**Comment by kutakmir** [comment]
works like a charm! Great work!

**Comment by akiroom** [comment]
Thank you for your nice comment!
