### ISSUE TITLE
UIViewController with UIScrollView

### ISSUE THREAD

**Issue by johannwilfling** [akiroom/AXStretchableHeaderTabViewController#18]
For a subview controller, I've added a UIScrollView to an plain UIViewController that conforms to the 'AXStretchableSubViewControllerViewSource' protocol.

Within the stretchableSubViewInSubViewController:subViewController method, the reference to the UIScrollView is returned.

However, the 'stretch' and 'move' effect of the header view is not triggered - what am I missing?

Nice and great control, anyway! ;-)

**Comment by akiroom** [comment]
It is similar to AXSub4ViewController in Example.
I need more information.
Could you check the bottom list?
- `UIScrollView` has enough `contentSize` to scroll
- `stretchableSubViewInSubViewController:` method returns **not nil** scroll view.
- `UIScrollView` is addded in `UIViewController`'s `view`.

**Comment by johannwilfling** [comment]
Thanks for your hints - I've messed something up .. :-(
