### ISSUE TITLE
AXDummyViewController.h file not found when pod try

### ISSUE THREAD

**Issue by siutsin** [akiroom/AXStretchableHeaderTabViewController#3]
/tmp/CocoaPods/Try/AXStretchableHeaderTabViewController/Example/StretchableHeaderTabViewExample/AXSampleListViewController.m:7:9: 'AXStretchableHeaderTabViewController/AXDummyViewController.h' file not found

**Comment by akiroom** [comment]
Thank you for your issue.
It's my fault. I'll fix soon.

**Comment by akiroom** [comment]
I fixed it. Thank you.
